import type { ResearchResult } from "@/types";

export async function generatePdfReport(data: ResearchResult): Promise<Buffer> {
  const html = buildHtml(data);
  return generatePdf(html);
}

function buildHtml(data: ResearchResult): string {
  const { company, competitors } = data;

  const rows = [
    ["Company Name", company.name],
    ["Website", company.website],
    ["Phone", company.phone || "N/A"],
    ["Address", company.address || "N/A"],
    ["Industry", company.industry || "N/A"],
    ["Summary", company.summary || "N/A"],
    ["Products", company.products.join(", ") || "N/A"],
    ["Services", company.services.join(", ") || "N/A"],
    ["Pain Points", company.painPoints.join(", ") || "N/A"],
  ];

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Company Research Report - ${company.name}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a1a; }
    h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; font-size: 28px; }
    h2 { color: #374151; margin-top: 30px; font-size: 20px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th { background: #f3f4f6; text-align: left; padding: 10px 12px; font-weight: 600; border: 1px solid #d1d5db; }
    td { padding: 10px 12px; border: 1px solid #d1d5db; vertical-align: top; }
    .label { font-weight: 600; width: 180px; background: #f9fafb; }
    .competitor-card { display: inline-block; background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px; padding: 16px; margin: 8px; width: 220px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #d1d5db; font-size: 12px; color: #6b7280; text-align: center; }
    .pain-point { background: #fef2f2; border-left: 4px solid #ef4444; padding: 8px 12px; margin: 6px 0; border-radius: 4px; }
    .tag { display: inline-block; background: #dbeafe; color: #1d4ed8; padding: 4px 10px; border-radius: 12px; font-size: 13px; margin: 3px; }
  </style>
</head>
<body>
  <h1>Company Research Report</h1>
  <p style="color: #6b7280; font-size: 14px;">Generated: ${new Date(data.generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}</p>

  <h2>Company Information</h2>
  <table>
    ${rows.map(([label, value]) => `<tr><td class="label">${label}</td><td>${value}</td></tr>`).join("")}
  </table>

  ${company.products.length > 0 ? `<h2>Products</h2>${company.products.map((p) => `<span class="tag">${p}</span>`).join("")}` : ""}
  ${company.services.length > 0 ? `<h2>Services</h2>${company.services.map((s) => `<span class="tag">${s}</span>`).join("")}` : ""}
  ${company.painPoints.length > 0 ? `<h2>AI-Generated Pain Points</h2>${company.painPoints.map((p) => `<div class="pain-point">${p}</div>`).join("")}` : ""}

  ${competitors.length > 0 ? `<h2>Competitors</h2>${competitors.map((c) => `<div class="competitor-card"><strong>${c.name}</strong><br><span style="font-size:13px;color:#2563eb;">${c.website}</span></div>`).join("")}` : ""}

  <div class="footer">
    <p>Generated by Company Research Assistant &bull; Data collected from public sources</p>
  </div>
</body>
</html>`;
}

async function generatePdf(html: string): Promise<Buffer> {
  const isVercel = process.env.VERCEL === "1";
  if (isVercel) {
    throw new Error("Server-side PDF not available on Vercel; client-side fallback used");
  }
  return generateWithPlaywright(html);
}

async function generateWithPlaywright(html: string): Promise<Buffer> {
  try {
    const { chromium } = await import("playwright-core");
    const browser = await chromium.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "load" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
    });
    await browser.close();
    return Buffer.from(pdf);
  } catch {
    throw new Error("Server-side PDF generation failed");
  }
}
